version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - backend
            - frontend
    frontend:
        image: node:current-alpine
        user: ${WWWUSER}:${WWWGROUP}
        working_dir: /home/node/app
        volumes:
        - ./frontend:/home/node/app
        environment:
            NODE_ENV: development
        command: "npm run dev"
    backend:
        build:
            context: ./.docker/laravel
        user: ${WWWUSER}:${WWWGROUP}
        volumes:
            - '.:/app'
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
